version: '3'
services:
  db:
    image: "postgres"
    ports:
      - "5440:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgVolume:/var/lib/postgresql/data

  expense-manager-api:
    container_name: expense-manager-api-container
    build:
      context: expense-manager-api
      dockerfile: Dockerfile
    image: expense-manager-api:latest
    ports:
      - 18080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    restart: always
  expense-manager-ui:
    container_name: expense-manager-ui-container
    build:
      context: expense-manager-ui
      dockerfile: Dockerfile
    image: expense-manager-ui:latest
    ports:
      - 13000:3000
    depends_on:
      - expense-manager-api
